version: "3.9"
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik-tours
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache curl &&
        traefik --api.insecure=true \
                --providers.docker=true \
                --entrypoints.web.address=:80 \
                --entrypoints.traefik.address=:8080 \
                - "--log.level=DEBUG"

    ports:
      - "80:80"                                   # Puerto para acceder a los servicios (HTTP)
      - "8080:8080"                               # Dashboard de Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Permite a Traefik leer los servicios de Docker
    networks:
      - web

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-frontend
    labels:
      - "traefik.enable=true"                                  # Habilita Traefik para este servicio
      - "traefik.http.routers.frontend.rule=Host(`app.local`)" # Define el dominio personalizado
      - "traefik.http.services.frontend.loadbalancer.server.port=3000" # Puerto interno del servicio
      - "traefik.http.services.frontend.loadbalancer.server.scheme=http"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Permite hot-reload en Docker
    command: ["npm", "run", "dev"]
    networks:
      - web

networks:
  web:
    driver: bridge
